//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrum.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int taskId { get; set; }
        public string taskName { get; set; }
        public string taskDeadline { get; set; }
        public int workingId { get; set; }
        public int categoryId { get; set; }
        public int storyId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Story Story { get; set; }
        public virtual Working Working { get; set; }
    }
}
